export * from './client';
export * from './media/media';
export * from './types/interfaces';
export * from './types/enums';
export * from './conversations/conversation-update';
export * from 'softphone-vendor-headsets';
export * from './sessions/softphone-session-handler';
export * from './sessions/video-session-handler';
export * from './sessions/screen-recording-session-handler';
export * from './sessions/screen-share-session-handler';
export * from './sessions/live-monitoring-session-handler';
export * from './audio-processor/interface';
export { ExpandedDeviceConnectionStatus } from './headsets/headset-types';
import * as utils from './utils';
import * as mediaUtils from './media/media-utils';
import { JingleReason, JingleInfo } from 'stanza/protocol';
declare const JingleReasonCondition: {
    readonly AlternativeSession: "alternative-session";
    readonly Busy: "busy";
    readonly Cancel: "cancel";
    readonly ConnectivityError: "connectivity-error";
    readonly Decline: "decline";
    readonly Expired: "expired";
    readonly FailedApplication: "failed-application";
    readonly FailedTransport: "failed-transport";
    readonly GeneralError: "general-error";
    readonly Gone: "gone";
    readonly IncompatibleParameters: "incompatible-parameters";
    readonly MediaError: "media-error";
    readonly SecurityError: "security-error";
    readonly Success: "success";
    readonly Timeout: "timeout";
    readonly UnsupportedApplications: "unsupported-applications";
    readonly UnsupportedTransports: "unsupported-transports";
};
export { utils, mediaUtils, JingleReason, JingleReasonCondition, JingleInfo };
export { SdkError } from './utils';
import GenesysCloudWebrtSdk from './client';
export default GenesysCloudWebrtSdk;
